version: 2
updates:
  - package-ecosystem: pip
    directory: '/backend'
    schedule:
      interval: monthly
    target-branch: 'dev'

  - package-ecosystem: npm
    directory: '/'  
    schedule:
      interval: monthly
    target-branch: 'dev'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
