name: open-webui-dev

services:
  frontend:
    build:
      context: .
      target: build
    command: ["sh", "/app/src/frontend-dev.sh"]
    depends_on:
      - backend
    ports:
      - "3000:5173"
    extra_hosts:
      - host.docker.internal:127.0.0.1
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./vite.config.ts:/app/vite.config.ts
      - ./svelte.config.js:/app/svelte.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./tailwind.config.js:/app/tailwind.config.js

  backend:
    build:
      context: .
      target: base
    command: ["bash", "dev.sh"]
    env_file: ".env"
    environment:
      - ENV=dev
    ports:
      - "8080:8080"
    extra_hosts:
      - host.docker.internal:127.0.0.1
    volumes:
      - ./backend:/app/backend
      - data:/app/backend/data

volumes:
  data: {}
