resources:
  - namespace.yaml
  - ollama-service.yaml
  - ollama-statefulset.yaml
  - webui-deployment.yaml
  - webui-service.yaml
  - webui-ingress.yaml
  - webui-pvc.yaml
  - webui-secrets.yaml

namespace: gpt-portal
