name: "üêãBuild Docker image"

on:
  workflow_dispatch:
    inputs:
      nombre:
        type: string
        description: Nombre de la imagen a crear
        required: true
        default: turing
      tag:
        type: string
        description: Version o tag de la imagen
        required: true
        default: latest

env:
  IMAGE_NAME: ghcr.io/sintergicaai/${{ inputs.nombre }}

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login on DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: GTWALOM
          password: ${{ secrets.ANTON_TOKEN }}

      - name: Configure QEMU
        uses: docker/setup-qemu-action@v1

      - name: Configure buildx
        uses: docker/setup-buildx-action@v1.0.0

      - name: Start buildx
        uses: docker/build-push-action@v4.0.0
        id: build
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ inputs.tag }},${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64
          push: true