name: OpenWebUI Docker Build

on:
  workflow_dispatch:
  push:
    branches:
      - ionos-dev
    tags:
      - ionos-*

env:
  REGISTRY: reg.1u1.it
  NAMESPACES: moc-dev


jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read
      issues: write
    steps:
      - name: Set TIMESTAMP variable
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        id: install
        with:
          version: 'latest'

      - name: Create Docker Secret Config for Kaniko
        run: |
          mkdir -p $HOME/.docker
          AUTH="$(echo -n "${{ secrets.HARBOR_USERNAME }}:${{ secrets.HARBOR_PASSWORD }}" | base64)"
          echo "{\"auths\":{\"reg.1u1.it:443\":{\"auth\":\"${AUTH}\"}}}" > $HOME/.docker/config.json
          set +e
          kubectl get secret dock-sec -n arc-runners
          if [ $? -ne 0 ]; then
            kubectl create secret generic dock-sec --from-file=config.json=$HOME/.docker/config.json --namespace=arc-runners
          else
            echo "dock-sec already exists, skipping creation."
          fi
          set -e  

      - name: Create and Apply Kaniko Job
        run: |
          set +e
          # Check if the job exists
          kubectl get job openwebui-build-push-image -n arc-runners
          if [ $? -eq 0 ]; then
            echo "Job gpt-build-push-image, deleting it..."
            kubectl delete job openwebui-build-push-image -n arc-runners --ignore-not-found
          fi
                   
          
          # Create a new job
          echo "
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: openwebui-build-push-image
            namespace: arc-runners
          spec:
            template:
              spec:    
                containers:
                - name: kaniko
                  image: gcr.io/kaniko-project/executor:latest
                  args:
                  - --dockerfile=./Dockerfile
                  - --context=git://${{ secrets.GITHUB_TOKEN }}@github.com/IONOS-Productivity/gpt-open-webui.git
                  - --git=branch=${{ github.ref }}                
                  - --destination=reg.1u1.it:443/moc-dev/drive/open-webui:${{ github.run_id }}
                  - --destination=reg.1u1.it:443/moc-dev/drive/open-webui:latest
                  - --build-arg=BUILD_HASH=${{ github.sha }}
                  - --skip-tls-verify
                  volumeMounts:
                  - name: dock-sec
                    mountPath: /kaniko/.docker
                restartPolicy: Never
                volumes:
                - name: dock-sec
                  secret:
                    secretName: dock-sec
            backoffLimit: 1
          " | kubectl apply -f -
          set -e
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Monitor Job Status and Print Logs
        run: |
          echo "Monitoring build job."          
          set -e      
          JOB_NAME="openwebui-build-push-image"
          TIMEOUT=1200   # Set your desired timeout in seconds
          INTERVAL=30    # Interval for checking job status and printing logs

          until POD_NAME=$(kubectl get pods --namespace=arc-runners --selector=job-name=${JOB_NAME} --output=jsonpath='{.items[0].metadata.name}' 2>/dev/null); do
            echo "Waiting for pod to be created..."
            sleep 5
          done      
          echo "Pod ${POD_NAME} is created."      
          # Wait for pod to be running
          POD_STATUS=""
          until [ "$POD_STATUS" == "Running" ]; do
            POD_STATUS=$(kubectl get pod ${POD_NAME} -o jsonpath='{.status.phase}')
            if [ "$POD_STATUS" != "Running" ]; then
              echo "Waiting for pod ${POD_NAME} to be running. Current status: ${POD_STATUS}"
              sleep 5
            fi
          done      
          echo "Pod ${POD_NAME} is running."
          # Monitor the job status and print logs every 30 seconds
          start_time=$(date +%s)
          while true; do
            current_time=$(date +%s)
            elapsed=$((current_time - start_time))      
            # Print pod logs
            echo "=== Logs for pod ${POD_NAME} ==="
            kubectl logs --namespace=arc-runners ${POD_NAME}       
            # Check if the job is complete
            JOB_STATUS=$(kubectl get job --namespace=arc-runners ${JOB_NAME} -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}')
            if [[ "$JOB_STATUS" == "True" ]]; then
              echo "Job ${JOB_NAME} is complete."
              break
            fi      
            # Timeout check
            if [[ $elapsed -ge $TIMEOUT ]]; then
              echo "Job ${JOB_NAME} did not complete within timeout. Exiting."
              exit 1
            fi      
            echo "Job is not complete yet. Checking again in ${INTERVAL}s..."
            sleep $INTERVAL
          done      
          echo "Image is pushed to the Harbor Registry with TAG '${{ github.run_id }}'"

      - name: Delete Kaniko Job
        run: |
          kubectl delete job openwebui-build-push-image --namespace=arc-runners --ignore-not-found
          kubectl delete secret -n arc-runners dock-sec --ignore-not-found        
          echo "All tasks completed gracefully."